export { default as AboutUs } from '@pages/AboutUs/AboutUs'
export { default as Contact } from '@pages/Contact/Contact'
export { default as Home } from '@pages/Home/Home'
export { default as OurShop } from '@pages/OurShop/OurShop'
export { default as ForgotPassword } from '@pages/ForgotPassword/ForgotPassword'